spring:
  datasource:
    url: jdbc:mysql://localhost:3306/querydsl
    username: root
    password: Coco123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
#        use_sql_comments: true //jpql sql문 확인하기
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

decorator:
  datasource:
    # p6spy 설정 적용
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j